// Context API
export const { CONTEXT_NAME } = process.env
export const { CONTEXT_VERSION } = process.env

// Comunicaciones.Service
export const {
  EMAIL_REMITENTE,
  URL_API_COMUNICACIONES,
  TEMPLATE_API_COMUNICACIONES_SMS,
  TEMPLATE_API_COMUNICACIONES_EMAIL,
  TEMPLATE_API_COMUNICACIONES_EMAIL_ACTIVACION,
  ACTIVACION_ENVIAROTP_MOSTRAROTP,
  ACTIVACION_BLOQUEO_REINTENTOS,
  ACTIVACION_EVENTOS_TIMETOLIVE,
  OTP_DURACION_SEGUNDOS,
  OTP_DURACION,
  OTP_SECRETO,
  OTP_DIGITOS,
  SOAPCRM_OPTIONS_TIMEOUT,
  SOAPCRM_HTTPHEADER_HOST,
  SOAPCRM_URL,
  RESTCRM_HOST_URL,
  RESTCRM_HTTPHEADER_OAUTHTOKEN_CLIENT_ID,
  RESTCRM_HTTPHEADER_OAUTHTOKEN_CLIENT_SECRET,
  RESTCRM_HTTPHEADER_USUARIO,
  RESTCRM_HTTPHEADER_DESTINO,
  RESTCRM_HTTPHEADER_CONSUMIDOR,
  BIND_PORT,
  BIND_URL
} = process.env

// CODE Response
export const CODE_CREATED = 'NMP.CUENTASDIGITALES.201'
export const CODE_SUCCESS = 'NMP.CUENTASDIGITALES.200'
export const CODE_NOT_CONTENT = 'NMP.CUENTASDIGITALES.204'
// Operation Status
export const CREATED = 'CREATED'
export const SUCCESS = 'SUCCESS'
export const NOT_CONTENT = 'NOT FOUND'

// Headers
export const HEADER_OAUTH = 'oauth.bearer'
export const HEADER_ID_CONSUMIDOR = 'idConsumidor'
export const HEADER_ID_DESTINO = 'idDestino'
export const HEADER_USUARIO = 'usuario'
export const HEADER_AUTHORIZATION = 'Authorization'
export const HEADER_ID_CLIENTE = 'idCliente'

// Cliente Estado Activacion
export const ESTADO_ACTIVACION_PROSPECTO = 2
export const ESTADO_ACTIVACION_OTPGENERADO = 3
export const ESTADO_ACTIVACION_ACTIVADO = 4
export const ESTADO_ACTIVACION_BLOQUEADO = 5
export const ESTADO_ACTIVACION_ERROR = 6

export const CRM_FLUJOESTADO_PROSPECTO = 1
export const CRM_FLUJOESTADO_OTPGENERADO = 2
export const CRM_FLUJOESTADO_ACTIVADO = 3

export const { URL_BASE_API_CLIENTES } = process.env
export const { AUTHORIZATION } = process.env

// NEW RELIC
export const { NEW_RELIC_LICENSE_KEY } = process.env
export const { LOG_LEVEL } = process.env

// REDIS
export const { REDIS_EX } = process.env
